[project]
name = "safearchive"
version = "0.1.0"
description = "Securely backup and manage your files locally with NAS support."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "art==6.5",
    "colorama==0.4.6",
    "humanize==4.14.0",
    "prettytable==3.17.0",
    "psutil==7.1.3",
    "pyinstaller>=6.17.0",
    "pyqt6>=6.10.1",
    "pyzipper==0.3.6",
    "qtawesome>=1.4.0",
    "schedule==1.2.2",
]
